name: deploy-toy-website-end-to-end-39
concurrency: toy-company

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

jobs:

  # Build the application and database.
  build:
    uses: ./.github/workflows/build39.yml

  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint39.yml

  # Deploy to the test environment.
  deploy-test:
    uses: ./.github/workflows/deploy39.yml
    needs: [build, lint]
    with:
      environmentType: Test
      resourceGroupName: ToyWebsiteTest
      location: 'westeurope'
      reviewApiUrl: https://sandbox.contoso.com/reviews
      sqlServerAdministratorLogin: TestToyCompanyAdmin
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_IDTY }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: ./.github/workflows/deploy39.yml
    needs:
      - lint
      - build
      - deploy-test
    with:
      environmentType: Prod
      resourceGroupName: ToyWebsiteProd
      location: 'westeurope'
      reviewApiUrl: https://api.contoso.com/reviews
      sqlServerAdministratorLogin: ToyCompanyAdmin
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PROD }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_IDTY }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PROD }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_PRODUCTION }}
